Dropped windows support

diff --git a/.github/workflows/cmakemulitplatform.yml b/.github/workflows/cmakemulitplatform.yml
--- a/.github/workflows/cmakemulitplatform.yml
+++ b/.github/workflows/cmakemulitplatform.yml
@@ -1,122 +1,141 @@
+# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
+# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
 name: CMake on multiple platforms
 
 on:
-  pull_request:
-    branches:
-      - actions-test
-
   push:
     branches:
       - actions-test
+          
+  pull_request:
+    branches:
+      - actions-test
+      
+
 
 jobs:
   build:
-    runs-on: ${{ matrix.sys.os }}
+    runs-on: ${{ matrix.os }}
 
     permissions:
+    
       contents: read
 
+      
     strategy:
-      # Set fail-fast to true when workflow is stable.
+      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
       fail-fast: false
 
-      # Set up a matrix to run the following configurations:
-      # 
-      # 1. <Windows, Debug / Release, latest GCC compiler toolchain>
-      # 2. <Linux, Debug / Release, latest GCC compiler toolchain>
-      # 3. <Linux, Debug / Release, latest Clang compiler toolchain>
-      # 
+      # Set up a matrix to run the following 3 configurations:
+      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
+      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
+      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
+      #
+      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
       matrix:
-        sys:
-          - { os: windows-latest, shell: bash }
-          - { os: ubuntu-latest, shell: bash }
+        os: [ubuntu-latest]
+        build_type: [Debug]
+        c_compiler: [gcc,clang,cl]
+        include:
+        
+          - os: ubuntu-latest
+            c_compiler: gcc
+            cpp_compiler: g++
 
-        # build_type: [ Debug, Release ]
-        build_type: [ Debug ]
-
-        compiler:
-          - { cc: gcc, cxx: g++ }
-          # - { cc: clang, cxx: clang++ }
-
-    defaults:
-      run:
-        # shell: ${{ matrix.sys.shell }}
-        shell: ${{ matrix.sys.shell }}
-
+          - os: ubuntu-latest
+            c_compiler: clang
+            cpp_compiler: clang++
+            
+        exclude:
+          - os: ubuntu-latest
+            c_compiler: cl
+            
     steps:
-      - uses: actions/checkout@v4
-        with:
-          clean: true
+    
+    - uses: actions/checkout@v4
+      with:
+        clean: true
 
-      # From: https://github.com/marketplace/actions/install-vulkan-sdk
-      - name: Install Vulkan SDK
-        uses: humbletim/install-vulkan-sdk@v1.2
-        with:
-          version: 1.3.296.0
-          cache: true
-          quiet: true
+        
+    - name: Set reusable strings
+      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
+      id: strings
+      shell: bash
+      run: |
+        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
 
-      - name: Test Vulkan SDK Install
-        shell: bash
-        run: |
-          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
-          echo "VULKAN_SDK=='$VULKAN_SDK'"
-          test -n "$VULKAN_SDK_VERSION"
-          glslangValidator --version
-      - if: runner.os == 'Linux'
-        name: Install Linux Developer Packages
-        run: |
-          sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
-      - name: Cache Submodules
-        id: cache-submodules
-        uses: actions/cache@v4.2.3
-        with:
-          # A list of files, directories, and wildcard patterns to cache and restore
-          path: |
-            Ocean/vendor
-          # An explicit key for restoring and saving the cache
-          key: ${{ github.ref_name }}-${{ runner.os }}-submodules
-          # Enables caching across platforms
-          enableCrossOsArchive: true
-          # Fail the workflow if a cache entry is not found
-          fail-on-cache-miss: false
+        
+    - name: per os installs (Windows and Linux)
+      #temporary until i get something.
 
-      - name: Update Git Submodules
-        if: steps.cache-submodules.outputs.cache-hit != 'true'
-        uses: actions/checkout@v4
-        with:
-          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
-          # recursively checkout submodules.
-          #
-          # When the `ssh-key` input is not provided, SSH URLs beginning with
-          # `git@github.com:` are converted to HTTPS.
-          #
-          # Default: false
-          submodules: recursive
 
-      # From: https://github.com/marketplace/actions/setup-cpp-c-c
-      - name: Setup Build System
-        uses: aminya/setup-cpp@v1
-        with:
-          compiler: ${{ matrix.compiler.cc }}
-          cmake: true
-          ninja: true
 
-      # From: https://github.com/marketplace/actions/cmake-action
-      - name: Configure CMake
-        uses: threeal/cmake-action@v2.1.0
-        with:
-          generator: Ninja
-          c-compiler: ${{ matrix.compiler.cc }}
-          cxx-compiler: ${{ matrix.compiler.cxx }}
+      #FORCES UPDATE, probably should put this in a variable.
+      #structure: Overall command
+                    #important future commands
+                    #Other deps that may need previous deps.
+      
+      run: |
+        if [ "$RUNNER_OS" == "Linux" ]; then
 
-          options: |
-            CMAKE_BUILD_TYPE=${{ matrix.build_type }}
-            Ocean_BUILD_DLL=ON
-            Ocean_BUILD_DOCS=OFF
-            Ocean_BUILD_TESTS=ON
-      # From: https://github.com/marketplace/actions/ctest-action
-      # - name: Test Project
-      #   uses: threeal/ctest-action@v1.1.0
-      #   with:
-      #     build-config: $${{ matrix.build_type }}
+          
+          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
+          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
+          sudo apt update
+          sudo apt install -y vulkan-sdk
+
+          
+          sudo apt install -y libwayland-dev libxkbcommon-dev xorg-dev
+
+          sudo apt-get update
+          
+        elif [ "$RUNNER_OS" == "Windows" ]; then
+          echo "Windows :) set up msys2 to actually test this."
+        else
+          echo "$RUNNER_OS is not supported."
+          exit 1
+        fi
+      shell: bash
+        
+
+
+    #this tries to force the necessary packages to be downloaded via the submodules.
+    - name: download necessary packages (ALL SYSTEMS)
+    #quick test.
+      shell: bash
+      run: |
+        git submodule update --force --recursive --init
+
+
+
+
+
+    - name: Configure CMake
+      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
+      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
+      
+      #new fix, see if this ensures that it uses the correct generator, and actually finds the compiler this time,
+      #instead of trying to use bash.
+      run: >
+        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
+          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
+          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
+          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
+          -DOcean_BUILD_DLL=ON \
+          -DOcean_BUILD_DOCS=OFF \
+          -DOcean_BUILD_TESTS=ON \
+          -S ${{ github.workspace }}
+
+    - name: check2
+      run: |
+        echo "Config FINISHED"
+      
+    - name: Build
+      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
+      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
+
+    #- name: Test
+   #   working-directory: ${{ steps.strings.outputs.build-output-dir }}
+      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
+      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+   #   run: ctest --build-config ${{ matrix.build_type }}
